Feature/1203706068707545 machine reward pallet
peaqnetwork/peaq-pallet-mor pull request #3
Opened 2023-01-26 14:23 UTC by michaeleberhardt310

2023-01-26 16:00 UTC, irediaes requested changes

2023-01-26 16:00 UTC, irediaes commented on src/lib.rs
>                  UnsufficientTokensInPot => Error::<T>::UnsufficientTokensInPot.into(),
UnsufficientTokensInPot ->> **InsufficientTokensInPot
Typo error

2023-01-26 16:00 UTC, irediaes commented on src/lib.rs
> +                <RewardsRecord<T>>::set((1u8, vec![<CrtBalance<T>>::from(0u128); N_BLOCKS]));
The type suffix should be removed since Balance is generic type.
If the Balance generic type is not set to u128, it will throw an exception.

`<RewardsRecord<T>>::set((1u8, vec![<CrtBalance<T>>::from(0); N_BLOCKS]));`

2023-01-26 16:00 UTC, irediaes commented on src/lib.rs
> +            let mut period_reward = <CrtBalance<T>>::from(0u128);
The type suffix should be removed since Balance is generic type.
If the Balance generic type is not set to u128, it will throw an exception.

`let mut period_reward = <CrtBalance<T>>::from(0);`

2023-01-26 16:00 UTC, irediaes commented on src/lib.rs
> +                Ok(<CrtBalance<T>>::from(100_000_000_000_000_000_u128))
The type suffix should be removed since Balance is generic type.
If the Balance generic type is not set to u128, it will throw an exception.

`Ok(<CrtBalance<T>>::from(100_000_000_000_000_000))`

Also, this default value should actually be a supplied by config, so that chains whose Balance type is not u128 can use this pallet. If this will take more time to achieve, it should be added to the backlog.

2023-01-26 16:37 UTC, neutrinoks commented on src/lib.rs
> +                Ok(<CrtBalance<T>>::from(100_000_000_000_000_000_u128))
I am working on a configuration solution, but Kamran is very pushy at the moment... I would add it in the next round

2023-01-27 09:32 UTC, irediaes approved these changes

2023-01-27 09:33 UTC, merged